In [1]:
import torch

In [2]:
# part a: C_jk = \sum_i A_ijk * b_i

A_ijk = torch.arange(24).reshape(2,3,4)
b_i = torch.arange(2)
C_jk = torch.einsum('ijk,i->jk', [A_ijk,b_i])

print(A_ijk.shape) # (2,3,4)
print(b_i.shape) # (2,)
print(C_jk.shape) # (3,4)

print(A_ijk)
print(b_i)
print(C_jk)

torch.Size([2, 3, 4])
torch.Size([2])
torch.Size([3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([0, 1])
tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


In [3]:
# part b: A_ik = \sum_jl A_ijkl

A_ijkl = torch.arange(120).reshape(2,3,4,5)
A_ik = torch.einsum('ijkl->ik', [A_ijkl])

print(A_ijkl.shape) # (2,3,4,5)
print(A_ik.shape) # (2,4)

print(A_ijkl)
print(A_ik)

torch.Size([2, 3, 4, 5])
torch.Size([2, 4])
tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])
tensor([[ 330,  405,  480,  555],
        [1230, 1305

In [4]:
# part c: A_ki = \sum_jl A_ijkl

A_ijkl = torch.arange(120).reshape(2,3,4,5)
A_ki = torch.einsum('ijkl->ki', [A_ijkl])

print(A_ijkl.shape) # (2,3,4,5)
print(A_ki.shape) # (4,2)

print(A_ijkl)
print(A_ki)

torch.Size([2, 3, 4, 5])
torch.Size([4, 2])
tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])
tensor([[ 330, 1230],
        [ 405, 1305],
        [

In [5]:
# part d: C_i = \sum_jk A_ijk * A_ijk

A_ijk = torch.arange(24).reshape(2,3,4)
C_i = torch.einsum('ijk,ijk->i', [A_ijk,A_ijk])

print(A_ijk.shape) # (2,3,4)
print(C_i.shape) # (2,)

print(A_ijk)
print(C_i)

torch.Size([2, 3, 4])
torch.Size([2])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([ 506, 3818])


In [6]:
# part e: C_dl = \sum A_de * G_fe^T * B_fl

A_de = torch.arange(6).reshape(2,3)
G_fe = torch.arange(12).reshape(4,3)
B_fl = torch.arange(20).reshape(4,5)
C_dl = torch.einsum('de,ef,fl->dl',[A_de, G_fe.T, B_fl])

print(A_de.shape) # (2,3)
print(G_fe.T.shape) # (3,4)
print(B_fl.shape) # (4,5)
print(C_dl.shape) # (2,5)

print(A_de)
print(G_fe.T)
print(B_fl)
print(C_dl)

torch.Size([2, 3])
torch.Size([3, 4])
torch.Size([4, 5])
torch.Size([2, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 780,  854,  928, 1002, 1076],
        [2940, 3212, 3484, 3756, 4028]])
